# Generated by Django 3.0.4 on 2020-09-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0005_auto_20200901_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric4',
            name='metric',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
