# Generated by Django 3.0.4 on 2020-09-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0007_auto_20200910_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric4',
            name='user',
        ),
        migrations.RemoveField(
            model_name='metric5',
            name='user',
        ),
        migrations.RemoveField(
            model_name='metric6',
            name='user',
        ),
        migrations.DeleteModel(
            name='Metric2',
        ),
        migrations.DeleteModel(
            name='Metric4',
        ),
        migrations.DeleteModel(
            name='Metric5',
        ),
        migrations.DeleteModel(
            name='Metric6',
        ),
    ]
