# Generated by Django 3.0.4 on 2020-09-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0008_auto_20200910_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/files'),
        ),
    ]
