# Generated by Django 3.0.4 on 2020-09-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0009_auto_20200924_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
